package com.eduhansol.app;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import com.eduhansol.app.entities.Admin;
import com.eduhansol.app.entities.Department;
import com.eduhansol.app.entities.Group;
import com.eduhansol.app.entities.Hq;
import com.eduhansol.app.entities.NormPersonality;
import com.eduhansol.app.entities.Region;
import com.eduhansol.app.entities.Role;
import com.eduhansol.app.entities.Tester;
import com.eduhansol.app.entities.TesterResult;
import com.eduhansol.app.repositories.NormPersonalityRepository;
import com.eduhansol.app.services.AdminService;
import com.eduhansol.app.services.DepartmentService;
import com.eduhansol.app.services.GroupService;
import com.eduhansol.app.services.HqService;
import com.eduhansol.app.services.RegionService;
import com.eduhansol.app.services.RoleService;
import com.eduhansol.app.services.TesterResultService;
import com.eduhansol.app.services.TesterService;
import com.eduhansol.app.viewmodels.SubFactorScoreViewModel;

import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.util.ResourceUtils;

@SpringBootTest
class HansolPersonalityApplicationTests {

	private NormPersonalityRepository normPersonalityRepository;
	private AdminService adminService;
	private RoleService roleService;

	private HqService hqService;
	private RegionService regionService;
	private DepartmentService departmentService;

	private TesterService _testerService;
	private TesterResultService _testerResultService;
	private GroupService _groupService;

	@Autowired
	public HansolPersonalityApplicationTests(NormPersonalityRepository normPersonalityRepository,
			AdminService adminService, RoleService roleService, HqService hqService, RegionService regionService,
			DepartmentService departmentService, TesterResultService testerResultService, TesterService testerService,
			GroupService groupService) {
		this.normPersonalityRepository = normPersonalityRepository;
		this.adminService = adminService;
		this.roleService = roleService;
		this.hqService = hqService;
		this.regionService = regionService;
		this.departmentService = departmentService;
		_testerResultService = testerResultService;
		_testerService = testerService;
		_groupService = groupService;
	}

	@Test
	void contextLoads() {
		// addHq();
		// addRegion();
		// addDepartment();
		// addRole();
		// addAdmin();
		// addNormPeronality();
		// updateAdminPassword();
	}

	void createPersonalReport() throws IOException, InvalidFormatException {
		Tester tester = _testerService.get(1);

        Group group = _groupService.get(tester.getGroup().getId());

        if (group == null)
            return;

        TesterResult testerResult = _testerResultService.findByTesterid(tester.getId());
        if (testerResult == null)
            return;

        // List<Narrative> narratives = _narrativeService.getList();
        // if(narratives.size() <= 0) return;

        List<SubFactorScoreViewModel> subFactorScoreViewModels = new ArrayList<>();
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(1, testerResult.getSubFactor1T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(2, testerResult.getSubFactor2T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(3, testerResult.getSubFactor3T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(4, testerResult.getSubFactor4T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(5, testerResult.getSubFactor5T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(6, testerResult.getSubFactor6T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(7, testerResult.getSubFactor7T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(8, testerResult.getSubFactor8T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(9, testerResult.getSubFactor9T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(10, testerResult.getSubFactor10T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(11, testerResult.getSubFactor11T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(12, testerResult.getSubFactor12T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(13, testerResult.getSubFactor13T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(14, testerResult.getSubFactor14T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(15, testerResult.getSubFactor15T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(23, testerResult.getSubFactor23T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(24, testerResult.getSubFactor24T()));
        subFactorScoreViewModels.add(new SubFactorScoreViewModel(25, testerResult.getSubFactor25T()));

        // 점수 높은 순으로 정렬
        subFactorScoreViewModels = subFactorScoreViewModels.stream()
                .sorted(Comparator.comparingDouble(SubFactorScoreViewModel::getTScore).reversed())
                .collect(Collectors.toList());

        String fileName = group.getId() + "_" + group.getName() + "_" + tester.getName() + "_" + tester.getAuthKey();
        File existFile = ResourceUtils.getFile("src/main/resources/" + fileName + ".xlsx");

        if (existFile.exists()) {
            Files.delete(new File("src/main/resources/" + fileName + ".xlsx").toPath());
        }

        FileNio2Copy("src/main/resources/personal_report.xlsx", "src/main/resources/" + fileName + ".xlsx");

        // File file = ResourceUtils.getFile("classpath:personal_report.xlsx");
        File file = ResourceUtils.getFile("src/main/resources/" + fileName + ".xlsx");
        
        XSSFWorkbook workbook = new XSSFWorkbook(file);
        XSSFSheet sheet = null;
        XSSFRow row = null;
        XSSFCell cell = null;

        // Cell Style
        XSSFCellStyle backgroundGray = workbook.createCellStyle();
        backgroundGray.setFillForegroundColor(new XSSFColor(new byte[] { (byte) 208, (byte) 206, (byte) 206 }, null));
        backgroundGray.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        XSSFCellStyle backgroundPink = workbook.createCellStyle();
        backgroundPink.setFillForegroundColor(new XSSFColor(new byte[] { (byte) 252, (byte) 228, (byte) 214 }, null));
        backgroundPink.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        sheet = workbook.getSheetAt(0);
        // 날짜
        row = sheet.getRow(7);
        cell = row.getCell(54);
        cell.setCellValue(tester.getCompletedDateTime());

        // 지원자 ID
        row = sheet.getRow(12);
        cell = row.getCell(8);
		cell.setCellValue(tester.getApplyId());
		
        // workbook.write(file);
        workbook.close();
	}
	
    private static void FileNio2Copy(String source, String dest) throws IOException {
        Files.copy(new File(source).toPath(), new File(dest).toPath());
    }

	void updateAdminPassword() {
		Admin admin = this.adminService.get(1);
		admin.setEmail("hsaa1122");
		admin.setPassword("hsaa1122");
		this.adminService.update(admin);
	}

	void addHq() {
		Hq hq1 = new Hq("인재육성실");
		Hq hq2 = new Hq("남부사업총국");
		Hq hq3 = new Hq("남부플라톤사업총국");
		Hq hq4 = new Hq("중앙사업총국");
		Hq hq5 = new Hq("중앙플라톤사업총국");
		Hq hq6 = new Hq("FC사업본부");

		this.hqService.save(hq1);
		this.hqService.save(hq2);
		this.hqService.save(hq3);
		this.hqService.save(hq4);
		this.hqService.save(hq5);
		this.hqService.save(hq6);
	}

	void addRegion() {
		Region region1 = new Region("교수교육WG", 1);
		Region region2 = new Region("경남지역국", 2);
		Region region3 = new Region("경북지역국", 2);
		Region region4 = new Region("전남지역국", 2);
		Region region5 = new Region("중부지역국", 2);
		Region region6 = new Region("경북플라톤광역", 3);
		Region region7 = new Region("대전플라톤광역", 3);
		Region region8 = new Region("부산플라톤광역", 3);
		Region region9 = new Region("전남플라톤광역", 3);
		Region region10 = new Region("전북플라톤광역", 3);
		Region region11 = new Region("창원플라톤광역", 3);
		Region region12 = new Region("강남지역국", 4);
		Region region13 = new Region("강북지역국", 4);
		Region region14 = new Region("경서지역국", 4);
		Region region15 = new Region("경인지역국", 4);
		Region region16 = new Region("강남플라톤광역", 5);
		Region region17 = new Region("강북플라톤광역", 5);
		Region region18 = new Region("강서플라톤광역", 5);
		Region region19 = new Region("경인플라톤광역", 5);
		Region region20 = new Region("동북플라톤광역", 5);
		Region region21 = new Region("분당플라톤광역", 5);
		Region region22 = new Region("서북플라톤광역", 5);
		Region region23 = new Region("안양플라톤광역", 5);
		Region region24 = new Region("거창한글지사", 6);
		Region region25 = new Region("논산지사", 6);
		Region region26 = new Region("대구동부지사", 6);
		Region region27 = new Region("대천지사", 6);
		Region region28 = new Region("부산금정영어지사", 6);
		Region region29 = new Region("부산동부지사", 6);
		Region region30 = new Region("수원지사", 6);
		Region region31 = new Region("장안용인영어지사", 6);
		Region region32 = new Region("안동지사", 6);
		Region region33 = new Region("안산지사", 6);
		Region region34 = new Region("원주지사", 6);
		Region region35 = new Region("천안지사", 6);
		Region region36 = new Region("충주지사", 6);
		Region region37 = new Region("통영지사", 6);
		Region region38 = new Region("파주지사", 6);
		Region region39 = new Region("평택지사", 6);
		Region region40 = new Region("제천N지사", 6);
		Region region41 = new Region("용인지사", 6);
		Region region42 = new Region("오산동탄지사", 6);
		Region region43 = new Region("아산지사", 6);
		Region region44 = new Region("당진지사", 6);
		Region region45 = new Region("천안평택영플지사", 6);
		Region region46 = new Region("비앤케이지사", 6);

		this.regionService.save(region1);
		this.regionService.save(region2);
		this.regionService.save(region3);
		this.regionService.save(region4);
		this.regionService.save(region5);
		this.regionService.save(region6);
		this.regionService.save(region7);
		this.regionService.save(region8);
		this.regionService.save(region9);
		this.regionService.save(region10);
		this.regionService.save(region11);
		this.regionService.save(region12);
		this.regionService.save(region13);
		this.regionService.save(region14);
		this.regionService.save(region15);
		this.regionService.save(region16);
		this.regionService.save(region17);
		this.regionService.save(region18);
		this.regionService.save(region19);
		this.regionService.save(region20);
		this.regionService.save(region21);
		this.regionService.save(region22);
		this.regionService.save(region23);
		this.regionService.save(region24);
		this.regionService.save(region25);
		this.regionService.save(region26);
		this.regionService.save(region27);
		this.regionService.save(region28);
		this.regionService.save(region29);
		this.regionService.save(region30);
		this.regionService.save(region31);
		this.regionService.save(region32);
		this.regionService.save(region33);
		this.regionService.save(region34);
		this.regionService.save(region35);
		this.regionService.save(region36);
		this.regionService.save(region37);
		this.regionService.save(region38);
		this.regionService.save(region39);
		this.regionService.save(region40);
		this.regionService.save(region41);
		this.regionService.save(region42);
		this.regionService.save(region43);
		this.regionService.save(region44);
		this.regionService.save(region45);
		this.regionService.save(region46);
	}

	void addDepartment() {
		Department department1 = new Department("-", 1);
		Department department2 = new Department("거제지점", 2);
		Department department3 = new Department("마산진해지점", 2);
		Department department4 = new Department("부산김해지점", 2);
		Department department5 = new Department("부산중앙지점", 2);
		Department department6 = new Department("부산지점", 2);
		Department department7 = new Department("진주지점", 2);
		Department department8 = new Department("창원지점", 2);
		Department department9 = new Department("구미지점", 3);
		Department department10 = new Department("대구지점", 3);
		Department department11 = new Department("울산남지점", 3);
		Department department12 = new Department("울산중앙지점", 3);
		Department department13 = new Department("포항지점", 3);
		Department department14 = new Department("광주광산지점", 4);
		Department department15 = new Department("광주북지점", 4);
		Department department16 = new Department("광주서지점", 4);
		Department department17 = new Department("광주영어지점", 4);
		Department department18 = new Department("남원정읍지점", 4);
		Department department19 = new Department("목포지점", 4);
		Department department20 = new Department("순천지점", 4);
		Department department21 = new Department("여수지점", 4);
		Department department22 = new Department("군산지점", 5);
		Department department23 = new Department("대전남지점", 5);
		Department department24 = new Department("대전유성지점", 5);
		Department department25 = new Department("대전지점", 5);
		Department department26 = new Department("서산지점", 5);
		Department department27 = new Department("세종지점", 5);
		Department department28 = new Department("익산지점", 5);
		Department department29 = new Department("전주중앙지점", 5);
		Department department30 = new Department("전주지점", 5);
		Department department31 = new Department("청주영어지점", 5);
		Department department32 = new Department("청주지점", 5);
		Department department33 = new Department("구미플라톤센터", 6);
		Department department34 = new Department("대구남플라톤센터", 6);
		Department department35 = new Department("대구동플라톤센터", 6);
		Department department36 = new Department("대구북플라톤센터", 6);
		Department department37 = new Department("대구서플라톤센터", 6);
		Department department38 = new Department("대구중앙아카데미센터", 6);
		Department department39 = new Department("대전세종아카데미센터", 7);
		Department department40 = new Department("대전플라톤센터", 7);
		Department department41 = new Department("서산플라톤센터", 7);
		Department department42 = new Department("세종플라톤센터", 7);
		Department department43 = new Department("유성플라톤센터", 7);
		Department department44 = new Department("청주아카데미센터", 7);
		Department department45 = new Department("청주플라톤센터", 7);
		Department department46 = new Department("동래플라톤센터", 8);
		Department department47 = new Department("부산울산아카데미센터", 8);
		Department department48 = new Department("양산플라톤센터", 8);
		Department department49 = new Department("울산플라톤센터", 8);
		Department department50 = new Department("포항플라톤센터", 8);
		Department department51 = new Department("해운대플라톤센터", 8);
		Department department52 = new Department("광주북플라톤센터", 9);
		Department department53 = new Department("광주서플라톤센터", 9);
		Department department54 = new Department("광주아카데미센터", 9);
		Department department55 = new Department("목포플라톤센터", 9);
		Department department56 = new Department("순천플라톤센터", 9);
		Department department57 = new Department("여수플라톤센터", 9);
		Department department58 = new Department("덕진플라톤센터", 10);
		Department department59 = new Department("완산군산플라톤센터", 10);
		Department department60 = new Department("전북아카데미센터", 10);
		Department department61 = new Department("김해플라톤센터", 11);
		Department department62 = new Department("진주마산플라톤센터", 11);
		Department department63 = new Department("창원거제아카데미센터", 11);
		Department department64 = new Department("창원플라톤센터", 11);
		Department department65 = new Department("강남영어지점", 12);
		Department department66 = new Department("강남지점", 12);
		Department department67 = new Department("강동하남지점", 12);
		Department department68 = new Department("경기광주지점", 12);
		Department department69 = new Department("분당지점", 12);
		Department department70 = new Department("성남지점", 12);
		Department department71 = new Department("송파지점", 12);
		Department department72 = new Department("안양지점", 12);
		Department department73 = new Department("제주지점", 12);
		Department department74 = new Department("강릉지점", 13);
		Department department75 = new Department("강북노원지점", 13);
		Department department76 = new Department("강북영어지점", 13);
		Department department77 = new Department("광진지점", 13);
		Department department78 = new Department("구리남양주지점", 13);
		Department department79 = new Department("동대문지점", 13);
		Department department80 = new Department("성북지점", 13);
		Department department81 = new Department("의정부지점", 13);
		Department department82 = new Department("관악영어지점", 14);
		Department department83 = new Department("관악지점", 14);
		Department department84 = new Department("구로지점", 14);
		Department department85 = new Department("마포지점", 14);
		Department department86 = new Department("연수지점", 14);
		Department department87 = new Department("은평지점", 14);
		Department department88 = new Department("인천남영어지점", 14);
		Department department89 = new Department("인천중앙지점", 14);
		Department department90 = new Department("강서영어지점", 15);
		Department department91 = new Department("강서지점", 15);
		Department department92 = new Department("김포지점", 15);
		Department department93 = new Department("부천지점", 15);
		Department department94 = new Department("부평지점", 15);
		Department department95 = new Department("서인천지점", 15);
		Department department96 = new Department("시흥지점", 15);
		Department department97 = new Department("인천북영어지점", 15);
		Department department98 = new Department("일산지점", 15);
		Department department99 = new Department("강남아카데미센터", 16);
		Department department100 = new Department("강남플라톤센터", 16);
		Department department101 = new Department("강동플라톤센터", 16);
		Department department102 = new Department("문정플라톤센터", 16);
		Department department103 = new Department("서초플라톤센터", 16);
		Department department104 = new Department("송파플라톤센터", 16);
		Department department105 = new Department("강북아카데미센터", 17);
		Department department106 = new Department("강북플라톤센터", 17);
		Department department107 = new Department("광진중랑플라톤센터", 17);
		Department department108 = new Department("성동플라톤센터", 17);
		Department department109 = new Department("강서아카데미센터", 18);
		Department department110 = new Department("구로플라톤센터", 18);
		Department department111 = new Department("마포플라톤센터", 18);
		Department department112 = new Department("목동플라톤센터", 18);
		Department department113 = new Department("영등포플라톤센터", 18);
		Department department114 = new Department("은평플라톤센터", 18);
		Department department115 = new Department("경인아카데미센터", 19);
		Department department116 = new Department("남동플라톤센터", 19);
		Department department117 = new Department("부천플라톤센터", 19);
		Department department118 = new Department("부평플라톤센터", 19);
		Department department119 = new Department("서인천플라톤센터", 19);
		Department department120 = new Department("시흥플라톤센터", 19);
		Department department121 = new Department("연수플라톤센터", 19);
		Department department122 = new Department("주안플라톤센터", 19);
		Department department123 = new Department("강릉플라톤센터", 20);
		Department department124 = new Department("경기북아카데미센터", 20);
		Department department125 = new Department("구리플라톤센터", 20);
		Department department126 = new Department("노원플라톤센터", 20);
		Department department127 = new Department("동북아카데미센터", 20);
		Department department128 = new Department("의정부플라톤센터", 20);
		Department department129 = new Department("분당아카데미센터", 21);
		Department department130 = new Department("분당플라톤센터", 21);
		Department department131 = new Department("성남플라톤센터", 21);
		Department department132 = new Department("수지플라톤센터", 21);
		Department department133 = new Department("강서플라톤센터", 22);
		Department department134 = new Department("김포플라톤센터", 22);
		Department department135 = new Department("덕양플라톤센터", 22);
		Department department136 = new Department("서북아카데미센터", 22);
		Department department137 = new Department("일산서플라톤센터", 22);
		Department department138 = new Department("제주플라톤센터", 22);
		Department department139 = new Department("관악플라톤센터", 23);
		Department department140 = new Department("광명플라톤센터", 23);
		Department department141 = new Department("산본플라톤센터", 23);
		Department department142 = new Department("안양아카데미센터", 23);
		Department department143 = new Department("안양플라톤센터", 23);
		Department department144 = new Department("-", 24);
		Department department145 = new Department("-", 25);
		Department department146 = new Department("-", 26);
		Department department147 = new Department("-", 27);
		Department department148 = new Department("-", 28);
		Department department149 = new Department("-", 29);
		Department department150 = new Department("-", 30);
		Department department151 = new Department("-", 31);
		Department department152 = new Department("-", 32);
		Department department153 = new Department("-", 33);
		Department department154 = new Department("-", 34);
		Department department155 = new Department("-", 35);
		Department department156 = new Department("-", 36);
		Department department157 = new Department("-", 37);
		Department department158 = new Department("-", 38);
		Department department159 = new Department("-", 39);
		Department department160 = new Department("-", 40);
		Department department161 = new Department("-", 41);
		Department department162 = new Department("-", 42);
		Department department163 = new Department("-", 43);
		Department department164 = new Department("-", 44);
		Department department165 = new Department("-", 45);
		Department department166 = new Department("-", 46);

		this.departmentService.save(department1);
		this.departmentService.save(department2);
		this.departmentService.save(department3);
		this.departmentService.save(department4);
		this.departmentService.save(department5);
		this.departmentService.save(department6);
		this.departmentService.save(department7);
		this.departmentService.save(department8);
		this.departmentService.save(department9);
		this.departmentService.save(department10);
		this.departmentService.save(department11);
		this.departmentService.save(department12);
		this.departmentService.save(department13);
		this.departmentService.save(department14);
		this.departmentService.save(department15);
		this.departmentService.save(department16);
		this.departmentService.save(department17);
		this.departmentService.save(department18);
		this.departmentService.save(department19);
		this.departmentService.save(department20);
		this.departmentService.save(department21);
		this.departmentService.save(department22);
		this.departmentService.save(department23);
		this.departmentService.save(department24);
		this.departmentService.save(department25);
		this.departmentService.save(department26);
		this.departmentService.save(department27);
		this.departmentService.save(department28);
		this.departmentService.save(department29);
		this.departmentService.save(department30);
		this.departmentService.save(department31);
		this.departmentService.save(department32);
		this.departmentService.save(department33);
		this.departmentService.save(department34);
		this.departmentService.save(department35);
		this.departmentService.save(department36);
		this.departmentService.save(department37);
		this.departmentService.save(department38);
		this.departmentService.save(department39);
		this.departmentService.save(department40);
		this.departmentService.save(department41);
		this.departmentService.save(department42);
		this.departmentService.save(department43);
		this.departmentService.save(department44);
		this.departmentService.save(department45);
		this.departmentService.save(department46);
		this.departmentService.save(department47);
		this.departmentService.save(department48);
		this.departmentService.save(department49);
		this.departmentService.save(department50);
		this.departmentService.save(department51);
		this.departmentService.save(department52);
		this.departmentService.save(department53);
		this.departmentService.save(department54);
		this.departmentService.save(department55);
		this.departmentService.save(department56);
		this.departmentService.save(department57);
		this.departmentService.save(department58);
		this.departmentService.save(department59);
		this.departmentService.save(department60);
		this.departmentService.save(department61);
		this.departmentService.save(department62);
		this.departmentService.save(department63);
		this.departmentService.save(department64);
		this.departmentService.save(department65);
		this.departmentService.save(department66);
		this.departmentService.save(department67);
		this.departmentService.save(department68);
		this.departmentService.save(department69);
		this.departmentService.save(department70);
		this.departmentService.save(department71);
		this.departmentService.save(department72);
		this.departmentService.save(department73);
		this.departmentService.save(department74);
		this.departmentService.save(department75);
		this.departmentService.save(department76);
		this.departmentService.save(department77);
		this.departmentService.save(department78);
		this.departmentService.save(department79);
		this.departmentService.save(department80);
		this.departmentService.save(department81);
		this.departmentService.save(department82);
		this.departmentService.save(department83);
		this.departmentService.save(department84);
		this.departmentService.save(department85);
		this.departmentService.save(department86);
		this.departmentService.save(department87);
		this.departmentService.save(department88);
		this.departmentService.save(department89);
		this.departmentService.save(department90);
		this.departmentService.save(department91);
		this.departmentService.save(department92);
		this.departmentService.save(department93);
		this.departmentService.save(department94);
		this.departmentService.save(department95);
		this.departmentService.save(department96);
		this.departmentService.save(department97);
		this.departmentService.save(department98);
		this.departmentService.save(department99);
		this.departmentService.save(department100);
		this.departmentService.save(department101);
		this.departmentService.save(department102);
		this.departmentService.save(department103);
		this.departmentService.save(department104);
		this.departmentService.save(department105);
		this.departmentService.save(department106);
		this.departmentService.save(department107);
		this.departmentService.save(department108);
		this.departmentService.save(department109);
		this.departmentService.save(department110);
		this.departmentService.save(department111);
		this.departmentService.save(department112);
		this.departmentService.save(department113);
		this.departmentService.save(department114);
		this.departmentService.save(department115);
		this.departmentService.save(department116);
		this.departmentService.save(department117);
		this.departmentService.save(department118);
		this.departmentService.save(department119);
		this.departmentService.save(department120);
		this.departmentService.save(department121);
		this.departmentService.save(department122);
		this.departmentService.save(department123);
		this.departmentService.save(department124);
		this.departmentService.save(department125);
		this.departmentService.save(department126);
		this.departmentService.save(department127);
		this.departmentService.save(department128);
		this.departmentService.save(department129);
		this.departmentService.save(department130);
		this.departmentService.save(department131);
		this.departmentService.save(department132);
		this.departmentService.save(department133);
		this.departmentService.save(department134);
		this.departmentService.save(department135);
		this.departmentService.save(department136);
		this.departmentService.save(department137);
		this.departmentService.save(department138);
		this.departmentService.save(department139);
		this.departmentService.save(department140);
		this.departmentService.save(department141);
		this.departmentService.save(department142);
		this.departmentService.save(department143);
		this.departmentService.save(department144);
		this.departmentService.save(department145);
		this.departmentService.save(department146);
		this.departmentService.save(department147);
		this.departmentService.save(department148);
		this.departmentService.save(department149);
		this.departmentService.save(department150);
		this.departmentService.save(department151);
		this.departmentService.save(department152);
		this.departmentService.save(department153);
		this.departmentService.save(department154);
		this.departmentService.save(department155);
		this.departmentService.save(department156);
		this.departmentService.save(department157);
		this.departmentService.save(department158);
		this.departmentService.save(department159);
		this.departmentService.save(department160);
		this.departmentService.save(department161);
		this.departmentService.save(department162);
		this.departmentService.save(department163);
		this.departmentService.save(department164);
		this.departmentService.save(department165);
		this.departmentService.save(department166);
	}

	void addRole() {
		Role role1 = new Role();
		role1.setName("ADMIN");
		role1.setDescription("최고 관리자");

		Role role2 = new Role();
		role2.setName("HQ");
		role2.setDescription("본부 관리자");

		Role role3 = new Role();
		role3.setName("REGION");
		role3.setDescription("지역국 관리자");

		Role role4 = new Role();
		role4.setName("DPT");
		role4.setDescription("부서 관리자");

		this.roleService.save(role1);
		this.roleService.save(role2);
		this.roleService.save(role3);
		this.roleService.save(role4);
	}

	void addAdmin() {
		Admin admin1 = new Admin("dhlee", "dhlee", 1, 1);
		this.adminService.post(admin1);
		// Admin admin1 = new Admin("dhlee", "dhlee", 1, 1);
		// Admin admin2 = new Admin("HSFB1001", "HSFB1001", 4, 2);
		// Admin admin3 = new Admin("HSFB2011", "HSFB2011", 4, 3);
		// Admin admin4 = new Admin("HSFB1241", "HSFB1241", 4, 4);
		// Admin admin5 = new Admin("HSFB1261", "HSFB1261", 4, 5);
		// Admin admin6 = new Admin("HSFB1991", "HSFB1991", 4, 6);
		// Admin admin7 = new Admin("HSFB1951", "HSFB1951", 4, 7);
		// Admin admin8 = new Admin("HSFB2001", "HSFB2001", 4, 8);
		// Admin admin9 = new Admin("HSFB1011", "HSFB1011", 4, 9);
		// Admin admin10 = new Admin("HSFB1021", "HSFB1021", 4, 10);
		// Admin admin11 = new Admin("HSFB1041", "HSFB1041", 4, 11);
		// Admin admin12 = new Admin("HSFB1051", "HSFB1051", 4, 12);
		// Admin admin13 = new Admin("HSFI1021", "HSFI1021", 4, 13);
		// Admin admin14 = new Admin("HSFB1562", "HSFB1562", 4, 14);
		// Admin admin15 = new Admin("HSFB1572", "HSFB1572", 4, 15);
		// Admin admin16 = new Admin("HSFB1582", "HSFB1582", 4, 16);
		// Admin admin17 = new Admin("HSFB1801", "HSFB1801", 4, 17);
		// Admin admin18 = new Admin("HSFI1031", "HSFI1031", 4, 18);
		// Admin admin19 = new Admin("HSFB1591", "HSFB1591", 4, 19);
		// Admin admin20 = new Admin("HSFB1601", "HSFB1601", 4, 20);
		// Admin admin21 = new Admin("HSFB1611", "HSFB1611", 4, 21);
		// Admin admin22 = new Admin("HSFB1391", "HSFB1391", 4, 22);
		// Admin admin23 = new Admin("HSFB1961", "HSFB1961", 4, 23);
		// Admin admin24 = new Admin("HSFB1701", "HSFB1701", 4, 24);
		// Admin admin25 = new Admin("HSFB1941", "HSFB1941", 4, 25);
		// Admin admin26 = new Admin("HSFI1101", "HSFI1101", 4, 26);
		// Admin admin27 = new Admin("HSFD1731", "HSFD1731", 4, 27);
		// Admin admin28 = new Admin("HSFB1431", "HSFB1431", 4, 28);
		// Admin admin29 = new Admin("HSFB2021", "HSFB2021", 4, 29);
		// Admin admin30 = new Admin("HSFB1442", "HSFB1442", 4, 30);
		// Admin admin31 = new Admin("HSFB1771", "HSFB1771", 4, 31);
		// Admin admin32 = new Admin("HSFB1981", "HSFB1981", 4, 32);
		// Admin admin33 = new Admin("HSFD2351", "HSFD2351", 4, 33);
		// Admin admin34 = new Admin("HSFD2361", "HSFD2361", 4, 34);
		// Admin admin35 = new Admin("HSFD2371", "HSFD2371", 4, 35);
		// Admin admin36 = new Admin("HSFD2381", "HSFD2381", 4, 36);
		// Admin admin37 = new Admin("HSFD2391", "HSFD2391", 4, 37);
		// Admin admin38 = new Admin("HSFD2921", "HSFD2921", 4, 38);
		// Admin admin39 = new Admin("HSFD2891", "HSFD2891", 4, 39);
		// Admin admin40 = new Admin("HSFD2551", "HSFD2551", 4, 40);
		// Admin admin41 = new Admin("HSFD2571", "HSFD2571", 4, 41);
		// Admin admin42 = new Admin("HSFD2581", "HSFD2581", 4, 42);
		// Admin admin43 = new Admin("HSFD2591", "HSFD2591", 4, 43);
		// Admin admin44 = new Admin("HSFD2881", "HSFD2881", 4, 44);
		// Admin admin45 = new Admin("HSFD2611", "HSFD2611", 4, 45);
		// Admin admin46 = new Admin("HSFD2281", "HSFD2281", 4, 46);
		// Admin admin47 = new Admin("HSFD2941", "HSFD2941", 4, 47);
		// Admin admin48 = new Admin("HSFD2291", "HSFD2291", 4, 48);
		// Admin admin49 = new Admin("HSFD2301", "HSFD2301", 4, 49);
		// Admin admin50 = new Admin("HSFD2411", "HSFD2411", 4, 50);
		// Admin admin51 = new Admin("HSFD2341", "HSFD2341", 4, 51);
		// Admin admin52 = new Admin("HSFD2631", "HSFD2631", 4, 52);
		// Admin admin53 = new Admin("HSFD2641", "HSFD2641", 4, 53);
		// Admin admin54 = new Admin("HSFD2911", "HSFD2911", 4, 54);
		// Admin admin55 = new Admin("HSFD2671", "HSFD2671", 4, 55);
		// Admin admin56 = new Admin("HSFD2681", "HSFD2681", 4, 56);
		// Admin admin57 = new Admin("HSFD2701", "HSFD2701", 4, 57);
		// Admin admin58 = new Admin("HSFD2661", "HSFD2661", 4, 58);
		// Admin admin59 = new Admin("HSFD2711", "HSFD2711", 4, 59);
		// Admin admin60 = new Admin("HSFD2901", "HSFD2901", 4, 60);
		// Admin admin61 = new Admin("HSFD2801", "HSFD2801", 4, 61);
		// Admin admin62 = new Admin("HSFD2401", "HSFD2401", 4, 62);
		// Admin admin63 = new Admin("HSFD2931", "HSFD2931", 4, 63);
		// Admin admin64 = new Admin("HSFD2331", "HSFD2331", 4, 64);
		// Admin admin65 = new Admin("HSFD1598", "HSFD1598", 4, 65);
		// Admin admin66 = new Admin("HSFI1041", "HSFI1041", 4, 66);
		// Admin admin67 = new Admin("HSFB1971", "HSFB1971", 4, 67);
		// Admin admin68 = new Admin("HSFI1081", "HSFI1081", 4, 68);
		// Admin admin69 = new Admin("HSFB1181", "HSFB1181", 4, 69);
		// Admin admin70 = new Admin("HSFB1201", "HSFB1201", 4, 70);
		// Admin admin71 = new Admin("HSFB1211", "HSFB1211", 4, 71);
		// Admin admin72 = new Admin("HSFB1221", "HSFB1221", 4, 72);
		// Admin admin73 = new Admin("HSFB1621", "HSFB1621", 4, 73);
		// Admin admin74 = new Admin("HSFB1281", "HSFB1281", 4, 74);
		// Admin admin75 = new Admin("HSFB2031", "HSFB2031", 4, 75);
		// Admin admin76 = new Admin("HSFD1597", "HSFD1597", 4, 76);
		// Admin admin77 = new Admin("HSFB1841", "HSFB1841", 4, 77);
		// Admin admin78 = new Admin("HSFB2041", "HSFB2041", 4, 78);
		// Admin admin79 = new Admin("HSFB1711", "HSFB1711", 4, 79);
		// Admin admin80 = new Admin("HSFB1351", "HSFB1351", 4, 80);
		// Admin admin81 = new Admin("HSFB1371", "HSFB1371", 4, 81);
		// Admin admin82 = new Admin("HSFD1831", "HSFD1831", 4, 82);
		// Admin admin83 = new Admin("HSFB1481", "HSFB1481", 4, 83);
		// Admin admin84 = new Admin("HSFB1501", "HSFB1501", 4, 84);
		// Admin admin85 = new Admin("HSFB1521", "HSFB1521", 4, 85);
		// Admin admin86 = new Admin("HSFB1651", "HSFB1651", 4, 86);
		// Admin admin87 = new Admin("HSFB1541", "HSFB1541", 4, 87);
		// Admin admin88 = new Admin("HSFB1791", "HSFB1791", 4, 88);
		// Admin admin89 = new Admin("HSFB2051", "HSFB2051", 4, 89);
		// Admin admin90 = new Admin("HSFD1600", "HSFD1600", 4, 90);
		// Admin admin91 = new Admin("HSFB1071", "HSFB1071", 4, 91);
		// Admin admin92 = new Admin("HSFB1081", "HSFB1081", 4, 92);
		// Admin admin93 = new Admin("HSFB1101", "HSFB1101", 4, 93);
		// Admin admin94 = new Admin("HSFB1111", "HSFB1111", 4, 94);
		// Admin admin95 = new Admin("HSFB1121", "HSFB1121", 4, 95);
		// Admin admin96 = new Admin("HSFB1131", "HSFB1131", 4, 96);
		// Admin admin97 = new Admin("HSFD1595", "HSFD1595", 4, 97);
		// Admin admin98 = new Admin("HSFB1551", "HSFB1551", 4, 98);
		// Admin admin99 = new Admin("HSFD2851", "HSFD2851", 4, 99);
		// Admin admin100 = new Admin("HSFD1851", "HSFD1851", 4, 100);
		// Admin admin101 = new Admin("HSFD1861", "HSFD1861", 4, 101);
		// Admin admin102 = new Admin("HSFD2971", "HSFD2971", 4, 102);
		// Admin admin103 = new Admin("HSFD1901", "HSFD1901", 4, 103);
		// Admin admin104 = new Admin("HSFD1921", "HSFD1921", 4, 104);
		// Admin admin105 = new Admin("HSFD2811", "HSFD2811", 4, 105);
		// Admin admin106 = new Admin("HSFD2001", "HSFD2001", 4, 106);
		// Admin admin107 = new Admin("HSFD2011", "HSFD2011", 4, 107);
		// Admin admin108 = new Admin("HSFD2071", "HSFD2071", 4, 108);
		// Admin admin109 = new Admin("HSFD2861", "HSFD2861", 4, 109);
		// Admin admin110 = new Admin("HSFD2131", "HSFD2131", 4, 110);
		// Admin admin111 = new Admin("HSFD2171", "HSFD2171", 4, 111);
		// Admin admin112 = new Admin("HSFD2181", "HSFD2181", 4, 112);
		// Admin admin113 = new Admin("HSFD2201", "HSFD2201", 4, 113);
		// Admin admin114 = new Admin("HSFD2211", "HSFD2211", 4, 114);
		// Admin admin115 = new Admin("HSFD2951", "HSFD2951", 4, 115);
		// Admin admin116 = new Admin("HSFD2461", "HSFD2461", 4, 116);
		// Admin admin117 = new Admin("HSFD2471", "HSFD2471", 4, 117);
		// Admin admin118 = new Admin("HSFD2481", "HSFD2481", 4, 118);
		// Admin admin119 = new Admin("HSFD2491", "HSFD2491", 4, 119);
		// Admin admin120 = new Admin("HSFD2501", "HSFD2501", 4, 120);
		// Admin admin121 = new Admin("HSFD2511", "HSFD2511", 4, 121);
		// Admin admin122 = new Admin("HSFD2531", "HSFD2531", 4, 122);
		// Admin admin123 = new Admin("HSFD1991", "HSFD1991", 4, 123);
		// Admin admin124 = new Admin("HSFD2961", "HSFD2961", 4, 124);
		// Admin admin125 = new Admin("HSFD2021", "HSFD2021", 4, 125);
		// Admin admin126 = new Admin("HSFD2051", "HSFD2051", 4, 126);
		// Admin admin127 = new Admin("HSFD2821", "HSFD2821", 4, 127);
		// Admin admin128 = new Admin("HSFD2101", "HSFD2101", 4, 128);
		// Admin admin129 = new Admin("HSFD2831", "HSFD2831", 4, 129);
		// Admin admin130 = new Admin("HSFD1891", "HSFD1891", 4, 130);
		// Admin admin131 = new Admin("HSFD1911", "HSFD1911", 4, 131);
		// Admin admin132 = new Admin("HSFD1931", "HSFD1931", 4, 132);
		// Admin admin133 = new Admin("HSFD2421", "HSFD2421", 4, 133);
		// Admin admin134 = new Admin("HSFD2451", "HSFD2451", 4, 134);
		// Admin admin135 = new Admin("HSFD2151", "HSFD2151", 4, 135);
		// Admin admin136 = new Admin("HSFD2871", "HSFD2871", 4, 136);
		// Admin admin137 = new Admin("HSFD2221", "HSFD2221", 4, 137);
		// Admin admin138 = new Admin("HSFD2521", "HSFD2521", 4, 138);
		// Admin admin139 = new Admin("HSFD2121", "HSFD2121", 4, 139);
		// Admin admin140 = new Admin("HSFD2791", "HSFD2791", 4, 140);
		// Admin admin141 = new Admin("HSFD2751", "HSFD2751", 4, 141);
		// Admin admin142 = new Admin("HSFD2841", "HSFD2841", 4, 142);
		// Admin admin143 = new Admin("HSFD1941", "HSFD1941", 4, 143);
		// Admin admin144 = new Admin("FCJH1011", "FCJH1011", 4, 144);
		// Admin admin145 = new Admin("FCJH1051", "FCJH1051", 4, 145);
		// Admin admin146 = new Admin("FCJH1072", "FCJH1072", 4, 146);
		// Admin admin147 = new Admin("FCJH1111", "FCJH1111", 4, 147);
		// Admin admin148 = new Admin("FCJH1151", "FCJH1151", 4, 148);
		// Admin admin149 = new Admin("FCJH1172", "FCJH1172", 4, 149);
		// Admin admin150 = new Admin("FCJH1209", "FCJH1209", 4, 150);
		// Admin admin151 = new Admin("FCJH1211", "FCJH1211", 4, 151);
		// Admin admin152 = new Admin("FCJH1221", "FCJH1221", 4, 152);
		// Admin admin153 = new Admin("FCJH1236", "FCJH1236", 4, 153);
		// Admin admin154 = new Admin("FCJH1262", "FCJH1262", 4, 154);
		// Admin admin155 = new Admin("FCJH1291", "FCJH1291", 4, 155);
		// Admin admin156 = new Admin("FCJH1311", "FCJH1311", 4, 156);
		// Admin admin157 = new Admin("FCJH1321", "FCJH1321", 4, 157);
		// Admin admin158 = new Admin("FCJH1331", "FCJH1331", 4, 158);
		// Admin admin159 = new Admin("FCJH1341", "FCJH1341", 4, 159);
		// Admin admin160 = new Admin("FCJH1361", "FCJH1361", 4, 160);
		// Admin admin161 = new Admin("FCJH1391", "FCJH1391", 4, 161);
		// Admin admin162 = new Admin("FCJH1394", "FCJH1394", 4, 162);
		// Admin admin163 = new Admin("FCJH1395", "FCJH1395", 4, 163);
		// Admin admin164 = new Admin("FCJH1396", "FCJH1396", 4, 164);
		// Admin admin165 = new Admin("FCJH1399", "FCJH1399", 4, 165);
		// Admin admin166 = new Admin("FCJH1400", "FCJH1400", 4, 166);

		// this.adminService.post(admin1);
		// this.adminService.post(admin2);
		// this.adminService.post(admin3);
		// this.adminService.post(admin4);
		// this.adminService.post(admin5);
		// this.adminService.post(admin6);
		// this.adminService.post(admin7);
		// this.adminService.post(admin8);
		// this.adminService.post(admin9);
		// this.adminService.post(admin10);
		// this.adminService.post(admin11);
		// this.adminService.post(admin12);
		// this.adminService.post(admin13);
		// this.adminService.post(admin14);
		// this.adminService.post(admin15);
		// this.adminService.post(admin16);
		// this.adminService.post(admin17);
		// this.adminService.post(admin18);
		// this.adminService.post(admin19);
		// this.adminService.post(admin20);
		// this.adminService.post(admin21);
		// this.adminService.post(admin22);
		// this.adminService.post(admin23);
		// this.adminService.post(admin24);
		// this.adminService.post(admin25);
		// this.adminService.post(admin26);
		// this.adminService.post(admin27);
		// this.adminService.post(admin28);
		// this.adminService.post(admin29);
		// this.adminService.post(admin30);
		// this.adminService.post(admin31);
		// this.adminService.post(admin32);
		// this.adminService.post(admin33);
		// this.adminService.post(admin34);
		// this.adminService.post(admin35);
		// this.adminService.post(admin36);
		// this.adminService.post(admin37);
		// this.adminService.post(admin38);
		// this.adminService.post(admin39);
		// this.adminService.post(admin40);
		// this.adminService.post(admin41);
		// this.adminService.post(admin42);
		// this.adminService.post(admin43);
		// this.adminService.post(admin44);
		// this.adminService.post(admin45);
		// this.adminService.post(admin46);
		// this.adminService.post(admin47);
		// this.adminService.post(admin48);
		// this.adminService.post(admin49);
		// this.adminService.post(admin50);
		// this.adminService.post(admin51);
		// this.adminService.post(admin52);
		// this.adminService.post(admin53);
		// this.adminService.post(admin54);
		// this.adminService.post(admin55);
		// this.adminService.post(admin56);
		// this.adminService.post(admin57);
		// this.adminService.post(admin58);
		// this.adminService.post(admin59);
		// this.adminService.post(admin60);
		// this.adminService.post(admin61);
		// this.adminService.post(admin62);
		// this.adminService.post(admin63);
		// this.adminService.post(admin64);
		// this.adminService.post(admin65);
		// this.adminService.post(admin66);
		// this.adminService.post(admin67);
		// this.adminService.post(admin68);
		// this.adminService.post(admin69);
		// this.adminService.post(admin70);
		// this.adminService.post(admin71);
		// this.adminService.post(admin72);
		// this.adminService.post(admin73);
		// this.adminService.post(admin74);
		// this.adminService.post(admin75);
		// this.adminService.post(admin76);
		// this.adminService.post(admin77);
		// this.adminService.post(admin78);
		// this.adminService.post(admin79);
		// this.adminService.post(admin80);
		// this.adminService.post(admin81);
		// this.adminService.post(admin82);
		// this.adminService.post(admin83);
		// this.adminService.post(admin84);
		// this.adminService.post(admin85);
		// this.adminService.post(admin86);
		// this.adminService.post(admin87);
		// this.adminService.post(admin88);
		// this.adminService.post(admin89);
		// this.adminService.post(admin90);
		// this.adminService.post(admin91);
		// this.adminService.post(admin92);
		// this.adminService.post(admin93);
		// this.adminService.post(admin94);
		// this.adminService.post(admin95);
		// this.adminService.post(admin96);
		// this.adminService.post(admin97);
		// this.adminService.post(admin98);
		// this.adminService.post(admin99);
		// this.adminService.post(admin100);
		// this.adminService.post(admin101);
		// this.adminService.post(admin102);
		// this.adminService.post(admin103);
		// this.adminService.post(admin104);
		// this.adminService.post(admin105);
		// this.adminService.post(admin106);
		// this.adminService.post(admin107);
		// this.adminService.post(admin108);
		// this.adminService.post(admin109);
		// this.adminService.post(admin110);
		// this.adminService.post(admin111);
		// this.adminService.post(admin112);
		// this.adminService.post(admin113);
		// this.adminService.post(admin114);
		// this.adminService.post(admin115);
		// this.adminService.post(admin116);
		// this.adminService.post(admin117);
		// this.adminService.post(admin118);
		// this.adminService.post(admin119);
		// this.adminService.post(admin120);
		// this.adminService.post(admin121);
		// this.adminService.post(admin122);
		// this.adminService.post(admin123);
		// this.adminService.post(admin124);
		// this.adminService.post(admin125);
		// this.adminService.post(admin126);
		// this.adminService.post(admin127);
		// this.adminService.post(admin128);
		// this.adminService.post(admin129);
		// this.adminService.post(admin130);
		// this.adminService.post(admin131);
		// this.adminService.post(admin132);
		// this.adminService.post(admin133);
		// this.adminService.post(admin134);
		// this.adminService.post(admin135);
		// this.adminService.post(admin136);
		// this.adminService.post(admin137);
		// this.adminService.post(admin138);
		// this.adminService.post(admin139);
		// this.adminService.post(admin140);
		// this.adminService.post(admin141);
		// this.adminService.post(admin142);
		// this.adminService.post(admin143);
		// this.adminService.post(admin144);
		// this.adminService.post(admin145);
		// this.adminService.post(admin146);
		// this.adminService.post(admin147);
		// this.adminService.post(admin148);
		// this.adminService.post(admin149);
		// this.adminService.post(admin150);
		// this.adminService.post(admin151);
		// this.adminService.post(admin152);
		// this.adminService.post(admin153);
		// this.adminService.post(admin154);
		// this.adminService.post(admin155);
		// this.adminService.post(admin156);
		// this.adminService.post(admin157);
		// this.adminService.post(admin158);
		// this.adminService.post(admin159);
		// this.adminService.post(admin160);
		// this.adminService.post(admin161);
		// this.adminService.post(admin162);
		// this.adminService.post(admin163);
		// this.adminService.post(admin164);
		// this.adminService.post(admin165);
		// this.adminService.post(admin166);

	}

	void addNormPeronality() {
		NormPersonality normPersonality = new NormPersonality();
		normPersonality.setName("Norm 2020 Q1");
		normPersonality.setMean(50);
		normPersonality.setDev(50);
		normPersonality.setConsistencyMean(50);
		normPersonality.setConsistencyDev(50);
		normPersonality.setTimeout(3000);
		normPersonality.setFailConsistencySten(1);
		normPersonality.setFailDev(0.3);
		normPersonality.setFailMark1Count(200);
		normPersonality.setFailExtremeMark1Count(250);
		normPersonality.setDelete(false);

		this.normPersonalityRepository.save(normPersonality);

		// normPersonality.setName("Norm 2020 Q1");
		// normPersonality.setMean(50);
		// normPersonality.setDev(50);
		// normPersonality.setConsistencyMean(50);
		// normPersonality.setConsistencyDev(50);
		// normPersonality.setTimeout(3000);
		// normPersonality.setFailConsistencySten(1);
		// normPersonality.setFailDev(0.3);
		// normPersonality.setFailMark1Count(200);
		// normPersonality.setFailExtremeMark1Count(250);
		// normPersonality.setDelete(false);

		// this.normPersonalityRepository.save(normPersonality);

		// normPersonality.setName("Norm 2020 Q1");
		// normPersonality.setMean(50);
		// normPersonality.setDev(50);
		// normPersonality.setConsistencyMean(50);
		// normPersonality.setConsistencyDev(50);
		// normPersonality.setTimeout(3000);
		// normPersonality.setFailConsistencySten(1);
		// normPersonality.setFailDev(0.3);
		// normPersonality.setFailMark1Count(200);
		// normPersonality.setFailExtremeMark1Count(250);
		// normPersonality.setDelete(false);

		// this.normPersonalityRepository.save(normPersonality);
	}

	void addSubFactor() {

	}

	void addFactor() {

	}
}
